"use client";

import { useRef, useState, useEffect } from "react";
import { cn } from "@/lib/utils";

type Props = {
  onSend: (text: string) => void;
  onStop: () => void;
  isStreaming: boolean;
  disabled?: boolean;
};

export default function InputArea({ onSend, onStop, isStreaming, disabled }: Props) {
  const [text, setText] = useState("");
  const ref = useRef<HTMLTextAreaElement>(null);

  // Auto-resize textarea
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = Math.min(el.scrollHeight, 240) + "px";
  }, [text]);

  function send() {
    const t = text.trim();
    if (!t || isStreaming || disabled) return;
    onSend(t);
    setText("");
  }

  function onKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  }

  return (
    <div className="flex-shrink-0 px-4 md:px-8 pb-4 md:pb-6 pt-3">
      <div className="max-w-3xl mx-auto">
        <div
          className={cn(
            "rounded-generous border bg-surface-elevated p-3 flex items-end gap-2",
            "transition-all",
            disabled ? "border-border-light opacity-60" : "border-border-light focus-within:border-electric-purple/60 focus-within:shadow-[0_0_0_3px_rgba(139,92,246,0.25)]"
          )}
        >
          <textarea
            ref={ref}
            value={text}
            onChange={(e) => setText(e.target.value)}
            onKeyDown={onKeyDown}
            placeholder={disabled ? "Out of credits. Complete a Yeumoney task to continue." : "Type a message…  (Enter to send · Shift+Enter for newline)"}
            rows={1}
            disabled={disabled}
            className="flex-1 bg-transparent border-0 outline-none resize-none text-text-primary placeholder:text-text-disabled px-2 py-2 text-body-compact max-h-[240px]"
          />
          {isStreaming ? (
            <button
              onClick={onStop}
              className="h-[42px] px-5 rounded-standard border border-border-light text-text-secondary hover:text-text-primary hover:border-border-strong hover:bg-surface-glass-hover text-h4 font-semibold transition-all flex-shrink-0"
            >
              Stop
            </button>
          ) : (
            <button
              onClick={send}
              disabled={!text.trim() || disabled}
              className={cn(
                "h-[42px] px-5 rounded-standard font-semibold text-h4 transition-all flex-shrink-0",
                text.trim() && !disabled
                  ? "bg-electric-purple text-white shadow-level-2 hover:bg-electric-purple-hover hover:shadow-level-3 active:bg-electric-purple-active"
                  : "bg-surface-glass text-text-tertiary cursor-not-allowed"
              )}
            >
              Send
            </button>
          )}
        </div>
        <p className="text-center text-[11px] text-text-tertiary mt-2.5">
          Output is generated by AI. Verify important information.
        </p>
      </div>
    </div>
  );
}
